[package]
name = "jfb"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
draco = { path = "../.." }
wasm-bindgen = { version = "0.2", features = ["enable-interning"] }

rand = "0.5"
web-sys = { version = "0.3", features = ["Window"] }
