[package]
name = "ref_focus"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
draco = { path = "../.." }
wasm-bindgen = "0.2"

web-sys = { version = "0.3", features = ["Element"] }
